---
# tasks file for mysql_server

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
  become: true

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: true
  become: true

# handlers:
#   - name: Restart MySQL service
#     service:
#       name: mysql
#       state: restarted
#     become: true

- name: Configure MySQL root password
  debconf:
    name: mysql-server
    question: 'mysql-server/root_password'
    value: 'ubuntu'
    vtype: password
  #notify: Restart MySQL service
  become: true

- name: Configure MySQL root user
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    state: present
  become: true

- name: Configure MySQL ansible user
  mysql_user:
    name: ansible
    password: "{{ ansible_user_password }}"
    priv: "*.*:ALL,GRANT"
    state: present
  become: true

- name: Restart MySQL service
  service:
    name: mysql
    state: restarted
  become: true