---
# tasks file for mysql_server

- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
  become: true

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: true
  become: true

# - name: Configure MySQL root password
#   debconf:
#     name: mysql-server
#     question: 'mysql-server/root_password'
#     value: 'ubuntu'
#     vtype: password
#   notify: Restart MySQL service
#   become: true

- name: Restart MySQL service
  service:
    name: mysql
    state: restarted
  become: true