---
# tasks file for mysql_server

# first, update the apt cache
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes

# install MySQL server
- name: Install MySQL server
  ansible.builtin.apt:
    name: mysql-server
    state: present
  become: true

- name: Ensure pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: yes

- name: Ensure pkg-config is installed
  ansible.builtin.apt:
    name: pkg-config
    state: present
  become: yes

- name: Ensure libmysqlclient-dev is installed
  ansible.builtin.apt:
    name: libmysqlclient-dev
    state: present
  become: yes

- name: Ensure mysqlclient is installed
  ansible.builtin.pip:
    name: mysqlclient
    state: present
  become: yes

# configure MySQL root password
- name: Change root user's password and authentication method
  mysql_user:
    name: root
    password: "{{ DB_PASS_ROOT }}"
    plugin: mysql_native_password
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: "{{ DB_PASS_ROOT }}"
  notify: Restart MySQL Service
  become: true

# - name: Start MySQL service
#   ansible.builtin.service:
#     name: mysql
#     state: started
#   become: true

# # - name: Wait for MySQL to start up
# #   ansible.builtin.wait_for:
# #     host: localhost
# #     port: 3306
# #     delay: 5


- name: Configure MySQL root user
  mysql_user:
    name: root
    password: "{{ DB_PASS_ROOT }}"
    priv: "*.*:ALL,GRANT"
    state: present
    login_user: root
    login_password: "{{ DB_PASS_ROOT }}"
  become: true

- name: Create a new database
  mysql_db:
    name: "{{ DB_NAME }}"
    state: present
    login_user: root
    login_password: "{{ DB_PASS_ROOT }}"

- name: Create a new user
  mysql_user:
    name: "{{ DB_USER }}"
    host: "%"
    password: "{{ DB_PASSWORD }}"
    priv: "{{ DB_NAME }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ DB_PASS_ROOT }}"

- name: Grant all privileges to root
  mysql_user:
    name: "{{ DB_USER }}"
    password: "{{ DB_PASS_ROOT }}"
    priv: "{{ DB_NAME }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ DB_PASS_ROOT }}"
  notify: Restart MySQL Service


- name: Allow remote connections to MySQL
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address\s*=\s*127\.0\.0\.1\s*$'
    line: 'bind-address = 0.0.0.0'
  become: yes
  notify: Restart MySQL Service
  