---
- name: Update all linux based servers
  hosts: linux_all
  become: true
  tasks:
    - name: Update apt cache if its older than 22 hours
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 79200

    - name: Upgrade all packages and distro
      ansible.builtin.apt:
        upgrade: dist
        

- name: Update all Windows servers
  hosts: windows_all
  tasks:
    # - name: Update all types of Windows updates and reboot if needed
    #   ansible.windows.win_updates:
    #     category_names: "*"
    #     state: installed
    #     reboot: true
    #     reboot_timeout: 1800

    - name: Install all security, critical, and rollup updates without a scheduled task
      ansible.windows.win_updates:
        category_names:
         - SecurityUpdates
         - CriticalUpdates
         - UpdateRollups
      become: true
      become_method: runas
      become_user: SYSTEM
    

     - name: Install all updates and reboot as many times as needed
       ansible.windows.win_updates:
         category_names: '*'
         reboot: true