#Incompleto 
---
- name: Create users on different servers
  hosts: all
  become: true

  tasks:
    - name: Create user on web server
      user:
        name: user1
        state: present
      when: inventory_hostname == 'web-server'

    - name: Create user on database server
      user:
        name: user2
        state: present
      when: inventory_hostname == 'database'

    - name: Create user on Windows server
      win_user:
        name: user3
        password: "{{ vaulted_password }}"
        state: present
      when: inventory_hostname == 'windows'