---
#Create users and groups defined in the inventory file (group_vars/linux.yml)
#Criar nova play à parte para criar os utilizadores de windows
- hosts: linux
  gather_facts: true
  become: true
  tasks:
    - name: Add groups to Ubuntu Servers
      ansible.builtin.group:
        name: "{{ item.name }}"
        state: present
      loop:
         - { name: dev } 
         - { name: dba }        
      
    - name: Create users and add to groups in Ubuntu
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        password: "{{ item.password }}"
        groups: "{{ item.groups }}"
        append: yes
      loop: "{{ users }}"
     
# - hosts: windows
#   gather_facts: true
#   tasks:
#     - name: Add groups to Ubuntu Servers
#       ansible.builtin.group:
#         name: "{{ item.name }}"
#         state: present
#       loop:
#          - { name: dev } 
#          - { name: dba }

#     - name: Create users and add to groups in Windows
#       ansible.windows.win_user:
#         name: "{{ item.name }}"
#         password: "{{ item.password }}"
#         groups: "{{ item.groups }}"
#         append: yes
#       loop: "{{ users }}"
    
    # - name: Add groups to Windows Servers
    #   ansible.windows.win_group:
    #     name: "{{ item.name }}"
    #     members: "{{ item.members }}"
    #     state: present
    #   loop:
    #      - { name: dev, members: "developer,dbdev" }
    #      - { name: dba, members: "dbadmin,dbdev" }
    #   when: ansible_os_family == 'Windows'

    # - name: Create dev and dba groups
    #   ansible.builtin.group:
    #     name: "{{ item.name }}"
    #     state: present
    #     members: "{{ item.members }}"
    #   loop: "{{ groups }}"

#Talvez a solução a baixo seja a melhor. Usar hash!
# ---
# - name: Create users and groups
#   hosts: all
#   tasks:
#      - name: Add users
#       ansible.builtin.user:
#         name: "{{ item.name }}"
#         password: "{{ item.password }}"
#         state: present
#       loop:
#         - { name: developer, password: Ansible2024 }
#         - { name: dbadmin, password: Ansible2024 }
#         - { name: dbdev, password: Ansible2024 }

