---
#Create users and groups defined in the inventory file (group_vars/linux.yml)
#Criar nova play à parte para criar os utilizadores de windows
- hosts: linux_prod
  gather_facts: true
  become: true
  tasks:
    - name: Add groups to Ubuntu Servers
      ansible.builtin.group:
        name: "{{ item.name }}"
        state: present
      loop:
         - { name: dev } 
         - { name: dba }        
    - name: Create users and add to groups in Ubuntu
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        password: "{{ item.password }}"
        groups: "{{ item.groups }}"
        append: yes
      loop: "{{ users }}"

- hosts: windows_prod
  gather_facts: true
  tasks:
    - name: Add groups to Windows Server
      ansible.builtin.win_group:
        name: "{{ item.name }}"
        state: present
      loop:
        - { name: dev } 
        - { name: dba }
    - name: Create users and add to groups in Windows
      ansible.windows.win_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        groups: "{{ item.groups }}"
      loop: "{{ users }}"
    
    - name: Restart Windows Server(s)
      ansible.windows.win_reboot:


