#Incompleto 
#falta dar acessos a pastas
---
- name: Create users on different servers
  hosts: all
  become: true

  tasks:
    - name: Create developer
      user:
        name: developer
        password: 
        state: present
      when: inventory_hostname in groups['all']

    - name: Create dbadmin
      user:
        name: dbadmin
        state: present
      when: inventory_hostname in groups['all']

    - name: Create dbdev
      win_user:
        name: dbdev
        state: present
      when: inventory_hostname in groups['all']