---
- name: Create users and groups
  hosts: all
  gather_facts: false

  vars:
    users:
      - name: developer
        password: !vault |
          $ANSIBLE_VAULT;1.1;AES256$ENCRYPTED_PASSWORD1$
      - name: dbadmin
        password: !vault |
          $ANSIBLE_VAULT;1.1;AES256$ENCRYPTED_PASSWORD2$
      - name: dbdev
        password: !vault |
          $ANSIBLE_VAULT;1.1;AES256$ENCRYPTED_PASSWORD3$

    groups:
      - name: dev
        members:
          - developer
          - dbdev
      - name: dba
        members:
          - dbadmin
          - dbdev

  tasks:
    - name: Create users
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        generate_ssh_key: yes
      loop: "{{ users }}"

    - name: Create groups
      group:
        name: "{{ item.name }}"
        state: present
        members: "{{ item.members }}"
      loop: "{{ groups }}"