---
#Create users and groups defined in the inventory file (group_vars/all.yml)
- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Create users in Ubuntu
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        password: "{{ item.password }}"
      loop: "{{ users }}"
      when: ansible_os_family == 'Debian'

    - name: Create users in Windows
      ansible.windows.win_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
      loop: "{{ users }}"
      when: ansible_os_family == 'Windows'

    - name: Create dev and dba groups
      group:
        name: "{{ groups.name }}"
        state: present
        members: "{{ groups.members }}"
      loop: "{{ groups }}"

