---
#Install and configure web server tasks for Apache Role
- name: Install Apache
  become: true
  ansible.builtin.apt:
    name: apache2
    state: latest

- name: Start Apache
  become: true
  ansible.builtin.service:
    name: apache2
    state: started

#Copy index.hmtl to webserver-linux (managed node)
# - name: Copy index.html
#   become: true
#   ansible.builtin.copy:
#     src: ./roles/apache/files/index.html
#     dest: /var/www/html/index.html
#   notify: Restart Apache

# - name: Run smoke test
#   ansible.builtin.uri:
#     url: http://localhost
#     return_content: yes
#   register: result

# - name: Debug smoke test
#   ansible.builtin.debug:
#     msg: "{{ result.content }}"

#Configure Apache for Wordpress
#Copy wordpress.conf to /etc/apache2/sites-available/wordpress.conf (in webserver-linux)
- name: Copy wordpress.conf to /etc/apache2/sites-available/wordpress.conf
  become: true
  ansible.builtin.copy:
    src: ./roles/apache/files/wordpress.conf
    dest: /etc/apache2/sites-available/wordpress.conf
  notify: Restart Apache

- name: Check if rewrite module is enabled
  ansible.builtin.stat:
    path: /etc/apache2/mods-enabled/rewrite.load
  register: rewrite_module

- name: Enable URL rewriting module
  become: true
  ansible.builtin.command:
    cmd: a2enmod rewrite
  notify: Restart Apache
  when: rewrite_module.stat.exists

- name: Check if default site is enabled
  ansible.builtin.stat:
    path: /etc/apache2/sites-enabled/000-default.conf
  register: default_site

#Disable the default “It Works” site
- name: Disable default apache site (000-default)
  become: true
  ansible.builtin.command:
    cmd: a2dissite 000-default
  notify: Restart Apache
  when: default_site.stat.exists

- name: Run smoke test after wordpress configuration
  ansible.builtin.uri:
    url: http://localhost
    return_content: yes
  register: result

- name: Debug smoke test after wordpress configuration
  ansible.builtin.debug:
    msg: "{{ result.content }}"

