---
# tasks file for mysql_server

# first, update the apt cache
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  

# install MySQL server
- name: Install MySQL server
  ansible.builtin.apt:
    name: mysql-server
    state: present

# Install the python3-pip package
- name: Ensure pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
  
# Install a helper tool to allow ansible libraries work with Mysql
- name: Ensure pkg-config is installed
  ansible.builtin.apt:
    name: pkg-config
    state: present
  
# More requeriments to install
- name: Ensure libmysqlclient-dev is installed
  ansible.builtin.apt:
    name: libmysqlclient-dev
    state: present
  

- name: Ensure mysqlclient is installed
  ansible.builtin.pip:
    name: mysqlclient
    state: present

# configure MySQL root password
- name: Change root user's password and authentication method
  mysql_user:
    name: root
    password: "{{ DB_PASS_ROOT }}"
    plugin: mysql_native_password
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: "{{ DB_PASS_ROOT }}"

- name: Configure MySQL root user
  mysql_user:
    name: root
    password: "{{ DB_PASS_ROOT }}"
    priv: "*.*:ALL,GRANT"
    state: present
    login_user: root
    login_password: "{{ DB_PASS_ROOT }}"

- name: Create a new database
  mysql_db:
    name: "{{ DB_NAME }}"
    state: present
    login_user: root
    login_password: "{{ DB_PASS_ROOT }}"

- name: Create a new user
  mysql_user:
    name: "{{ DB_USER }}"
    host: "%"
    password: "{{ DB_PASSWORD }}"
    priv: "{{ DB_NAME }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ DB_PASS_ROOT }}"

- name: Grant all privileges to root
  mysql_user:
    name: root
    password: "{{ DB_PASS_ROOT }}"
    priv: "{{ DB_NAME }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ DB_PASS_ROOT }}"
  

- name: Allow remote connections to MySQL
  ansible.builtin.lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address\s*=\s*127\.0\.0\.1\s*$'
    line: 'bind-address = 0.0.0.0'
  notify: Restart MySQL Service