---
- name: Update all linux based servers
  hosts: linux_all
  become: true
  tasks:
    - name: Update apt cache if its older than 22 hours
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 79200

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: yes
        
# - name: Update all Windows servers
#   hosts: windows_all
#   tasks:
#     # - name: Update all types of Windows updates and reboot if needed
#     #   ansible.windows.win_updates:
#     #     category_names: "*"
#     #     state: installed
#     #     reboot: true
#     #     reboot_timeout: 1800
#     - name: Download all security, critical, and rollup updates 
#       ansible.windows.win_updates:
#         category_names:
#           - SecurityUpdates
#           - CriticalUpdates
#           - UpdateRollups
#         state: downloaded
#       register: win_downloaded_updates
    
    # - name: Install all updates and reboot as many times as needed
    #   ansible.windows.win_updates:
    #     category_names: '*'
    #     reboot: true

  #   - name: Patching and Updating Windows systems
  # hosts: windows-os:&azure-prod
  # tasks:
  #   - name: Update Windows systems databases
  #     ansible.windows.win_updates:
  #       category_names: "*"
  #       state: searched
  #     register: win_updates_results

# - name: Patching and Updating Windows systems
#   hosts: windows_all
#   tasks:
#     - name: Update Windows systems databases
#       ansible.windows.win_updates:
#         category_names: "*"
#         state: searched
#       register: win_updates_results

#     - name: Reboot Windows if necessary
#       ansible.windows.win_reboot:
#       when:
#         - win_updates_results.reboot_required == true

#     - name: Install security updates
#       ansible.windows.win_updates:
#         category_names: "*"
#         state: installed
#       register: win_upgrades_results
#       when:
#         - win_updates_results.updates | length > 0


#     # - name: Reboot Windows if necessary
#     #   ansible.windows.win_reboot:
#     #   when:
#     #     - win_downloaded_updates.reboot_required == true

#     # - name: Install security updates
#     #   ansible.windows.win_updates:
#     #     category_names:
#     #       - SecurityUpdates
#     #       - CriticalUpdates
#     #       - UpdateRollups
#     #     state: installed
#     #   register: win_upgrades_results

- hosts: windows_all
  become: yes
  become_method: runas
  become_user: SYSTEM
  tasks:
    - name: Install PSWindowsUpdate module
      ansible.windows.win_shell: |
        $ProgressPreference = 'SilentlyContinue'
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
        Install-Module PSWindowsUpdate -Force -Confirm:$false
      args:
        executable: powershell
    
    - name: Install Windows updates
      ansible.windows.win_shell: |
        Install-WindowsUpdate -AcceptAll -AutoReboot
      args:
        executable: powershell

    - name: Reboot
      ansible.windows.win_reboot:
