---
# vars file for mysql_server
mysql_version: 8.0.36
mysql_port: 3306
mysql_data_dir: /var/lib/mysql
mysql_config_file: /etc/mysql/my.cnf
DB_NAME: wordpress
DB_USER: ansible
DB_PASSWORD: 123
DB_PASS_ROOT: 123