---
# tasks file for wordpress

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes


- name: Install Wordpress CLI
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: 0755

- name: Download Wordpress
  command: wp core download --allow-root --force
  become: yes
  args:
    chdir: /var/www/html/

- name: remove index.html
  file:
    path: /var/www/html/index.html
    state: absent

- name : Create wp-config.php
  command: wp config create --dbname={{ DB_NAME }} --dbuser={{ DB_USER }} --dbpass={{ DB_PASSWORD }} --dbhost=localhost --dbprefix=wp_ --force --allow-root
  become: yes
  args:
    chdir: /var/www/html/

- name: Install Wordpress
  command: wp core install --url={{ URL }} --title={{ TITLE }} --admin_user={{ ADMIN_USER }} --admin_password={{ ADMIN_PASSWORD }} --admin_email={{ ADMIN_EMAIL }}
  become: yes
  args:
    chdir: /var/www/html/

- name: Ensure /var/www/html/ is writable
  file:
    path: /var/www/html/
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
    mode: '0755'