---
# tasks file for wordpress

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  

- name: Install Wordpress CLI
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: 0755

#create a directory for wordpress
- name: Create a directory for wordpress
  ansible.builtin.stat:
    path: /var/www/html/
  register: dir_check

- name: Create a directory for wordpress
  ansible.builtin.file:
    path: /var/www/html/
    state: directory
    mode: '0755'
  when: dir_check.stat.exists == False

- name: Download Wordpress
  command: wp core download --allow-root --force
  args:
    chdir: /var/www/html/

- name: remove index.html
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent

- name : Create wp-config.php
  ansible.builtin.command: wp config create --dbname={{ DB_NAME }} --dbuser={{ DB_USER }} --dbpass={{ DB_PASSWORD }} --dbhost={{ DB_HOST }} --allow-root --force
  args:
    chdir: /var/www/html/
  notify: Restart Apache

- name: Install Wordpress
  ansible.builtin.command: wp core install --url={{ URL }} --title="{{ TITLE }}" --admin_user={{ ADMIN_USER }} --admin_password={{ ADMIN_PASSWORD }} --admin_email={{ ADMIN_EMAIL }} --allow-root
  args:
    chdir: /var/www/html/
  notify: Restart Apache

- name: Change file permissions to 644
  ansible.builtin.file:
    path: /var/www/html/
    mode: '0644'

- name: Change directory permissions to 755
  ansible.builtin.file:
    path: /var/www/html/
    mode: '0755'
    state: directory

- name: Change file owner and group
  ansible.builtin.file:
    path: /var/www/html/
    recurse: yes
    owner: www-data
    group: www-data

# - name: Run smoke test after wordpress configuration
#   ansible.builtin.uri:
#     url: http://localhost
#     return_content: yes
#   register: result

# - name: Debug smoke test after wordpress configuration
#   ansible.builtin.debug:
#     msg: "{{ result.content }}"
