all:
  hosts:
    database:
      ansible_host: 192.168.0.7
      ansible_user: ansible
      ansible_ssh_private_key_file: /opt/ansible.pem
      ansible_python_interpreter: /usr/bin/python3
    webserver:
      ansible_host: 192.168.0.6
      ansible_user: ansible
      ansible_ssh_private_key_file: /opt/ansible.pem
      ansible_python_interpreter: /usr/bin/python3
    windows:
      ansible_port: 5985
      ansible_host: 192.168.0.100
      ansible_user: ansible
      ansible_password: Password1234!
      ansible_connection: winrm
      ansible_winrm_server_cert_validation: ignore
      ansible_winrm_transport: ntlm
      ansible_winrm_scheme: http
