---
#Tasks to install Mysql Workbench and verify the installation
- name: Download Mysql Workbench MSI installer
  ansible.windows.win_get_url:
    url: https://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-workbench-community-8.0.28-winx64.msi
    dest: C:\mysql-workbench.msi

- name: Execute Installer
  ansible.windows.win_package:
    path: C:\mysql-workbench.msi
    arguments: /quiet
    state: present

- name: Verify Mysql Workbench installation
  ansible.windows.win_shell: |
    $version = (Get-WmiObject -Class Win32_Product | Where-Object {$_.Name -like "MySQL Workbench*"}).Version
    if ($version -eq "8.0.36") {
      Write-Host "The Mysql Workbench installation was successful"
    } else {
      Write-Host "The Mysql Workbench installation failed"
    }
  register: result

- name: Print installation result
  ansible.builtin.debug:
    var: result.stdout_lines