---
# tasks file for mysql_workbench
- name: Installing Mysql Worbench
  hosts: windows-server
  gather_facts: true
  tasks:
  - name: Download Mysql Worbench installer
    ansible.windows.win_get_url:
        url: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6.5/npp.8.6.5.Installer.x64.exe
        
        dest: C:\npp.7.9.1.Installer.x64.exe

  - name: Execute Installer
    ansible.windows.win_package: 
        path: C:\npp.7.9.1.Installer.x64.exe
        #Instalação silenciosa sem interação do utilizador
        arguments: /S
        state: present